services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: no
    networks:
      - internal

  db:
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    external: false