services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Samara
      - PYTHONUNBUFFERED=1
    restart: no
    networks:
      - internal
      - ulstu-bots-network

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
  ulstu-bots-network:
    external: true